<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FacilitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('facilities')->insert([
            [ // 1 
                'facility_name' => 'Rose Memorial Auditorium (RMA)',
                'description' => 'A venue typically used for large-scale events, performances, and ceremonies.',
                'maximum_rental_hour' => null,
                'category_id' => 1,
                'subcategory_id' => 4,
                'capacity' => 2300,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 3500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => null,
                'building_code' => 'RMA',
                'total_levels' => 2,
                'total_rooms' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 2
                'facility_name' => 'Old Valentine Building (OV)',
                'description' => '',
                'maximum_rental_hour' => 10,
                'category_id' => 1,
                'subcategory_id' => 2,
                'capacity' => 200,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 300.00,
                'rate_type' => 'Per Hour',
                'status_id' => 3,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => null,
                'building_code' => 'OV',
                'total_levels' => 2,
                'total_rooms' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 3
                'facility_name' => 'University Church (UC)',
                'description' => '',
                'maximum_rental_hour' => 12,
                'category_id' => 1,
                'subcategory_id' => 3,
                'capacity' => 50,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 400.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => 1,
                'building_code' => 'UC',
                'total_levels' => 1,
                'total_rooms' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 4
                'facility_name' => 'University Gymnasium (UG)',
                'description' => 'A multi-purpose sports facility for various athletic activities and events.',
                'maximum_rental_hour' => null,
                'category_id' => 5,
                'subcategory_id' => 19,
                'capacity' => 6200,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 10000.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => 1,
                'building_code' => 'UG',
                'total_levels' => 1,
                'total_rooms' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 5 
                'facility_name' => 'Halfmoon Drive (HD)',
                'description' => '',
                'maximum_rental_hour' => 12,
                'category_id' => 4,
                'subcategory_id' => 12,
                'capacity' => 100,
                'department_id' => 1,
                'location_type' => 'Outdoors',
                'external_fee' => 350.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => null,
                'building_code' => null,
                'total_levels' => null,
                'total_rooms' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 6
                'facility_name' => 'Mary Thomas Building (MT)',
                'description' => '',
                'maximum_rental_hour' => 12,
                'category_id' => 1,
                'subcategory_id' => 2,
                'capacity' => 20,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 250.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => 1,
                'floor_level' => 2,
                'building_code' => null,
                'total_levels' => null,
                'total_rooms' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
                // Residencies/Dorms - Franklin Hall Dorm Rooms (10 rooms)
            [ // 7
                'facility_name' => 'Franklin Hall Dorm 001',
                'description' => 'Standard dormitory room with basic amenities',
                'maximum_rental_hour' => null,
                'category_id' => 3, // Residencies/Dorms
                'subcategory_id' => 10, // Dorm Rooms
                'capacity' => 2,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 150.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => 1,
                'building_code' => 'FH',
                'total_levels' => 5,
                'total_rooms' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 8
                'facility_name' => 'Franklin Hall Dorm 002',
                'description' => 'Standard dormitory room with basic amenities',
                'maximum_rental_hour' => null,
                'category_id' => 3,
                'subcategory_id' => 10,
                'capacity' => 2,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 150.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => 1,
                'building_code' => 'FH',
                'total_levels' => 5,
                'total_rooms' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 9
                'facility_name' => 'Franklin Hall Dorm 003',
                'description' => 'Standard dormitory room with basic amenities',
                'maximum_rental_hour' => null,
                'category_id' => 3,
                'subcategory_id' => 10,
                'capacity' => 2,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 150.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => 1,
                'building_code' => 'FH',
                'total_levels' => 5,
                'total_rooms' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 10
                'facility_name' => 'Franklin Hall Dorm 004',
                'description' => 'Standard dormitory room with basic amenities',
                'maximum_rental_hour' => null,
                'category_id' => 3,
                'subcategory_id' => 10,
                'capacity' => 2,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 150.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => 2,
                'building_code' => 'FH',
                'total_levels' => 5,
                'total_rooms' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 11
                'facility_name' => 'Franklin Hall Dorm 005',
                'description' => 'Standard dormitory room with basic amenities',
                'maximum_rental_hour' => null,
                'category_id' => 3,
                'subcategory_id' => 10,
                'capacity' => 2,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 150.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => 2,
                'building_code' => 'FH',
                'total_levels' => 5,
                'total_rooms' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 12
                'facility_name' => 'Franklin Hall Dorm 006',
                'description' => 'Standard dormitory room with basic amenities',
                'maximum_rental_hour' => null,
                'category_id' => 3,
                'subcategory_id' => 10,
                'capacity' => 2,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 150.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => 2,
                'building_code' => 'FH',
                'total_levels' => 5,
                'total_rooms' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 13
                'facility_name' => 'Franklin Hall Dorm 007',
                'description' => 'Standard dormitory room with basic amenities',
                'maximum_rental_hour' => null,
                'category_id' => 3,
                'subcategory_id' => 10,
                'capacity' => 2,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 150.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => 3,
                'building_code' => 'FH',
                'total_levels' => 5,
                'total_rooms' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 14
                'facility_name' => 'Franklin Hall Dorm 008',
                'description' => 'Standard dormitory room with basic amenities',
                'maximum_rental_hour' => null,
                'category_id' => 3,
                'subcategory_id' => 10,
                'capacity' => 2,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 150.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => 3,
                'building_code' => 'FH',
                'total_levels' => 5,
                'total_rooms' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 15
                'facility_name' => 'Franklin Hall Dorm 009',
                'description' => 'Standard dormitory room with basic amenities',
                'maximum_rental_hour' => null,
                'category_id' => 3,
                'subcategory_id' => 10,
                'capacity' => 2,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 150.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => 3,
                'building_code' => 'FH',
                'total_levels' => 5,
                'total_rooms' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 16
                'facility_name' => 'Franklin Hall Dorm 010',
                'description' => 'Standard dormitory room with basic amenities',
                'maximum_rental_hour' => null,
                'category_id' => 3,
                'subcategory_id' => 10,
                'capacity' => 2,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 150.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => null,
                'floor_level' => 4,
                'building_code' => 'FH',
                'total_levels' => 5,
                'total_rooms' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],

                // Campus Rooms - Classrooms (5 rooms)
            [ // 17
                'facility_name' => 'MT101',
                'description' => 'Standard classroom with whiteboard and projector',
                'maximum_rental_hour' => 8,
                'category_id' => 2, // Campus Rooms
                'subcategory_id' => 6, // Classrooms
                'capacity' => 30,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 200.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => 1, // Rose Memorial Auditorium
                'floor_level' => 1,
                'building_code' => 'MT',
                'total_levels' => 3,
                'total_rooms' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 18
                'facility_name' => 'MT102',
                'description' => 'Standard classroom with whiteboard and projector',
                'maximum_rental_hour' => 8,
                'category_id' => 2,
                'subcategory_id' => 6,
                'capacity' => 30,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 200.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => 1,
                'floor_level' => 1,
                'building_code' => 'MT',
                'total_levels' => 3,
                'total_rooms' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 19
                'facility_name' => 'UG101',
                'description' => 'Lecture-style classroom with tiered seating',
                'maximum_rental_hour' => 8,
                'category_id' => 2,
                'subcategory_id' => 6,
                'capacity' => 50,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 300.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => 4, // University Gymnasium
                'floor_level' => 1,
                'building_code' => 'UG',
                'total_levels' => 2,
                'total_rooms' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 20
                'facility_name' => 'UG102',
                'description' => 'Lecture-style classroom with tiered seating',
                'maximum_rental_hour' => 8,
                'category_id' => 2,
                'subcategory_id' => 6,
                'capacity' => 50,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 300.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => 4,
                'floor_level' => 1,
                'building_code' => 'UG',
                'total_levels' => 2,
                'total_rooms' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ // 21
                'facility_name' => 'OV201',
                'description' => 'Standard classroom with natural lighting',
                'maximum_rental_hour' => 8,
                'category_id' => 2,
                'subcategory_id' => 6,
                'capacity' => 25,
                'department_id' => 1,
                'location_type' => 'Indoors',
                'external_fee' => 180.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'last_booked_at' => null,
                'created_by' => 1,
                'updated_by' => null,
                'deleted_by' => null,
                'parent_facility_id' => 2, // Old Valentine Building
                'floor_level' => 2,
                'building_code' => 'OV',
                'total_levels' => 2,
                'total_rooms' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
