<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ParentFacilitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('facilities')->insert([
            // ==================== 1. UNIVERSITY GYMNASIUM (Building) ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'UG',
                'total_levels' => 2,
                'facility_name' => 'University Gymnasium',
                'description' => 'A multi-purpose sports facility for various athletic activities and events.',
                'category_id' => 1, // Buildings
                'subcategory_id' => 5, // Sports Venues (Gymnasiums)
                'location_note' => 'University Gymnasium',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1, // Available
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ==================== 2. ROSE MEMORIAL AUDITORIUM ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'RMA',
                'total_levels' => 2,
                'facility_name' => 'Rose Memorial Auditorium',
                'description' => 'A venue used for large-scale events, performances, and ceremonies.',
                'category_id' => 1, // Buildings
                'subcategory_id' => 4, // Auditoriums
                'location_note' => 'Beside Henry Luce Library and University Gym',
                'capacity' => 2300,
                'location_type' => 'Indoors',
                'base_fee' => 3500.00,
                'rate_type' => 'Per Event',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // ==================== 3. EDUCATIONAL MEDIA CONFERENCE ROOM ====================
            [
                'parent_facility_id' => null,
                'floor_level' => 1,
                'facility_code' => 'EMC',
                'total_levels' => 1,
                'facility_name' => 'Educational Media Conference Room',
                'description' => 'A meeting space equipped with technology for presentations and media-related conferences.',
                'category_id' => 1, // Buildings
                'subcategory_id' => 2, // Conference Rooms
                'location_note' => 'Behind Dining Hall, in front of Big Field',
                'capacity' => 300,
                'location_type' => 'Indoors',
                'base_fee' => 1000.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 4. ALUMNI PROMENADE & CONCERT PARK ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'APCP',
                'total_levels' => null,
                'facility_name' => 'Alumni Promenade & Concert Park',
                'description' => 'An outdoor area designated for gatherings and public concerts.',
                'category_id' => 4, // Outside Spaces
                'subcategory_id' => 12, // Promenades
                'location_note' => 'Beside Alumni Hall, Main Gate',
                'capacity' => 300,
                'location_type' => 'Outdoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // ==================== 5. NEW VALENTINE BUILDING ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'NV',
                'total_levels' => 3,
                'facility_name' => 'New Valentine Building',
                'description' => 'Classroom facility designed for lectures, discussions, and academic learning activities.',
                'category_id' => 1, // Buildings
                'subcategory_id' => 2, // Academic Buildings
                'location_note' => 'New Valentine Building',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 6. OLD VALENTINE BUILDING ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'OV',
                'total_levels' => 2,
                'facility_name' => 'Old Valentine Building',
                'description' => 'Classroom facility designed for lectures, discussions, and academic learning activities.',
                'category_id' => 1,
                'subcategory_id' => 2,
                'location_note' => 'Old Valentine Building',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 7. HENRY LUCE LIBRARY ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'HLL',
                'total_levels' => 4,
                'facility_name' => 'Henry Luce Library',
                'description' => 'Academic library providing study spaces, research resources, and learning support services.',
                'category_id' => 1,
                'subcategory_id' => 5, // Libraries
                'location_note' => 'Henry Luce Library',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== OUTDOOR FACILITIES ====================

            // ==================== 8. BIG FIELD ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'BF',
                'total_levels' => null,
                'facility_name' => 'Big Field',
                'description' => 'A large open field for sports, recreation, and other outdoor events.',
                'category_id' => 5, // Sports Venues
                'subcategory_id' => 19, // Sports Fields
                'location_note' => 'Central Campus',
                'capacity' => 1,
                'location_type' => 'Outdoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 9. HALFMOON DRIVE ====================

            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'HD',
                'total_levels' => null,
                'facility_name' => 'Halfmoon Drive',
                'description' => 'Covered pathway around Halfmoon Field, from Main Gate to Gate 3',
                'category_id' => 4, // Outside Spaces
                'subcategory_id' => 11, // Open Fields
                'location_note' => 'Covered pathway around Halfmoon Field, from Main Gate to Gate 3',
                'capacity' => 1,
                'location_type' => 'Outdoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 10. HALFMOON FIELD ====================

            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'HF',
                'total_levels' => null,
                'facility_name' => 'Halfmoon Field',
                'description' => 'Located near Main gate and Gate 3. An open field for sports, recreation, and other outdoor events.',
                'category_id' => 5,
                'subcategory_id' => 19,
                'location_note' => 'Near Main Gate and Gate 3',
                'capacity' => 1,
                'location_type' => 'Outdoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 11. SWIMMING POOL ====================

            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'SP',
                'total_levels' => null,
                'facility_name' => 'Swimming Pool',
                'description' => 'A recreational and athletic facility for swimming and water activities.',
                'category_id' => 5,
                'subcategory_id' => 18, // Swimming Pools
                'location_note' => '',
                'capacity' => 1,
                'location_type' => 'Outdoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 12. UY CONFERENCE ROOM ====================

            [
                'parent_facility_id' => null,
                'floor_level' => 4,
                'facility_code' => 'UY',
                'total_levels' => 4,
                'facility_name' => 'UY Conference Room',
                'description' => 'A conference room used for meetings and presentations.',
                'category_id' => 2,
                'subcategory_id' => 7,
                'location_note' => '4th Floor, Dr. Uy Alfonso Building',
                'capacity' => 150,
                'location_type' => 'Indoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 13. ANCHETA PAGSUBERON HALL ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'APH',
                'total_levels' => 1,
                'facility_name' => 'Ancheta Pagsuberon Hall',
                'description' => 'Classroom facility designed for lectures, discussions, and academic learning activities.',
                'category_id' => 1,
                'subcategory_id' => 2,
                'location_note' => 'Ancheta Pagsuberon Hall',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 14. ELEMENTARY BUILDING ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'EL',
                'total_levels' => 4,
                'facility_name' => 'Elementary Building',
                'description' => 'Classroom facility designed for lectures, discussions, and academic learning activities.',
                'category_id' => 1,
                'subcategory_id' => 2,
                'location_note' => 'Elementary Building',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 15. ENGINEERING BUILDING ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'EN',
                'total_levels' => 4,
                'facility_name' => 'Engineering Building',
                'description' => 'Classroom facility designed for lectures, discussions, and academic learning activities.',
                'category_id' => 1, // Buildings
                'subcategory_id' => 2, // Academic Buildings
                'location_note' => 'Engineering Building',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 16. MARY THOMAS HALL ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'MT',
                'total_levels' => 2,
                'facility_name' => 'Mary Thomas Hall',
                'description' => 'Classroom facility designed for lectures, discussions, and academic learning activities.',
                'category_id' => 1,
                'subcategory_id' => 2,
                'location_note' => 'Mary Thomas Hall',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // ==================== 17. LORETO D. TUPAZ HALL ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'LDT',
                'total_levels' => 3,
                'facility_name' => 'Loreto D. Tupaz Hall',
                'description' => 'Classroom facility designed for lectures, discussions, and academic learning activities.',
                'category_id' => 1,
                'subcategory_id' => 2,
                'location_note' => 'Loreto D. Tupaz Hall',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 18. SOFTBALL FIELD ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'SF',
                'total_levels' => null,
                'facility_name' => 'Softball Field',
                'description' => 'A dedicated field for playing softball.',
                'category_id' => 5, // Sports Venues
                'subcategory_id' => 19, // Sports Fields
                'location_note' => 'Behind Tennis Court and Swimming Pool',
                'capacity' => 1,
                'location_type' => 'Outdoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 19. TENNIS COURT ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'TC',
                'total_levels' => null,
                'facility_name' => 'Tennis Court',
                'description' => 'A court for playing tennis.',
                'category_id' => 5,
                'subcategory_id' => 17, // Outdoor Courts
                'location_note' => 'Behind University Gym and Rose Memorial Auditorium',
                'capacity' => 1,
                'location_type' => 'Outdoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ==================== 20. UNIVERSITY CHURCH ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'UC',
                'total_levels' => null,
                'facility_name' => 'University Church',
                'description' => 'A church located on campus for religious services and community.',
                'category_id' => 1, // Buildings
                'subcategory_id' => 3, // Worship Spaces
                'location_note' => 'Facing Big Field, Centennial Walkway',
                'capacity' => 800,
                'location_type' => 'Indoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ==================== 21. ROBLEE HALL ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'ROB',
                'total_levels' => 2,
                'facility_name' => 'Roblee Hall',
                'description' => 'Classroom facility designed for lectures, discussions, and academic learning activities.',
                'category_id' => 1,
                'subcategory_id' => 2,
                'location_note' => 'Roblee Hall',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ==================== 22. DR. LENWOOD EDGE BUILDING ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'LEB',
                'total_levels' => 2,
                'facility_name' => 'Dr. Lenwood Edge Building',
                'description' => 'Classroom facility designed for lectures, discussions, and academic learning activities.',
                'category_id' => 1,
                'subcategory_id' => 2,
                'location_note' => 'Dr. Lenwood Edge Building',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ==================== 23. JOHNSON HALL ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'JHN',
                'total_levels' => 2,
                'facility_name' => 'Johnson Hall',
                'description' => 'Classroom facility designed for lectures, discussions, and academic learning activities.',
                'category_id' => 1,
                'subcategory_id' => 2,
                'location_note' => 'Johnson Hall',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ==================== 24. ALUMNI HALL ====================

            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'AH',
                'total_levels' => 2,
                'facility_name' => 'Alumni Hall',
                'description' => 'Classroom facility designed for lectures, discussions, and academic learning activities.',
                'category_id' => 1,
                'subcategory_id' => 2,
                'location_note' => 'Alumni Hall',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
           // ==================== 25. GAZEBOS ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'GAZ',
                'total_levels' => null,
                'facility_name' => 'Gazebos',
                'description' => 'An open-sided structure for shelter, relaxation, or small gatherings.',
                'category_id' => 4,
                'subcategory_id' => 10,
                'location_note' => '',
                'capacity' => 1,
                'location_type' => 'Outdoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 26. STUDENT CENTER ====================

            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'SC',
                'total_levels' => null,
                'facility_name' => 'Student Center',
                'description' => 'Central hub for student services, organization meetings, study areas, and campus events, supporting academic and extracurricular student activities.',
                'category_id' => 1,
                'subcategory_id' => 1, // Event Halls
                'location_note' => '',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 27. ELEMENTARY GYMNASIUM ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'EGYM',
                'total_levels' => null,
                'facility_name' => 'Elementary Gymnasium',
                'description' => 'Indoor facility for elementary-level physical education, sports practice, school programs, and assemblies for younger students.',
                'category_id' => 5,
                'subcategory_id' => 15, // Gymnasiums
                'location_note' => '',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 28. JUNIOR HIGHSCHOOL GYMNASIUM ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'JHSGYM',
                'total_levels' => null,
                'facility_name' => 'Junior Highschool Gymnasium',
                'description' => 'Indoor venue for junior high PE classes, athletic training, intramurals, competitions, and school-wide gatherings.',
                'category_id' => 5,
                'subcategory_id' => 15,
                'location_note' => 'Near Junior Highschool Complex',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 29. GRANDSTAND ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'GS',
                'total_levels' => null,
                'facility_name' => 'Grandstand',
                'description' => 'Open stage overlooking the big field, used for spectators during sports events, ceremonies, and major campus activities.',
                'category_id' => 5,
                'subcategory_id' => 15,
                'location_note' => 'In front of Engineering Building',
                'capacity' => 1,
                'location_type' => 'Outdoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 30. CAMPUS GROUNDS ====================

            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'GR',
                'total_levels' => null,
                'facility_name' => 'Campus Grounds',
                'description' => 'Open outdoor spaces used for recreation, events, informal gatherings, and various student and school activities.',
                'category_id' => 4,
                'subcategory_id' => 11, // Open Fields
                'location_note' => '',
                'capacity' => 1,
                'location_type' => 'Outdoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 31. PACKAGING ENGINEERING ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'PE',
                'total_levels' => null,
                'facility_name' => 'Packaging Engineering',
                'description' => 'Academic department/laboratory focused on packaging design, materials science, testing, and engineering instruction and research.',
                'category_id' => 1,
                'subcategory_id' => 2,
                'location_note' => '',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 32. ANCHETA BASKETBALL COURT ====================
            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'ABC',
                'total_levels' => null,
                'facility_name' => 'Ancheta Basketball Court',
                'description' => 'Outdoor court used for basketball training, intramural games, practice sessions, and community sports activities.',
                'category_id' => 5,
                'subcategory_id' => 17, // Outdoor Courts
                'location_note' => 'In front of Ancheta Hall',
                'capacity' => 1,
                'location_type' => 'Outdoors',
                'base_fee' => 500.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 33. LOPEZ MEMORIAL HALL ====================

            [
                'parent_facility_id' => null,
                'floor_level' => null,
                'facility_code' => 'LHB',
                'total_levels' => 3,
                'facility_name' => 'Lopez Memorial Hall',
                'description' => 'Classroom facility designed for lectures, discussions, and academic learning activities.',
                'category_id' => 1,
                'subcategory_id' => 2,
                'location_note' => 'Lopez Memorial Hall',
                'capacity' => 1,
                'location_type' => 'Indoors',
                'base_fee' => 0.00,
                'rate_type' => 'Per Hour',
                'status_id' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'last_booked_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}